name: CD Pipeline

on:
  workflow_run:
    workflows: ['Docker Image CI']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull z00one/minori-rag-app:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f minori-rag-app-container || true
      - name: Delete Old Docker Images
        run: |
          IMAGE_ID=$(sudo docker images -q z00one/minori-rag-app:latest)
          sudo docker images -q | grep -v $IMAGE_ID | xargs -r sudo docker rmi
      - name: Run Docker Container
        run: |
          sudo docker run -d \
          -p 3000:3000 \
          -p 5432:5432 \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          -e JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }} \
          -e JWT_ACCESS_EXPIRATION=${{ secrets.JWT_ACCESS_EXPIRATION }} \
          -e AWS_REGION=${{ secrets.AWS_REGION }} \
          -e AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }} \
          -e AWS_S3_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRET_ACCESS_KEY }} \
          -e AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }} \
          -e AWS_CLOUDFRONT=${{ secrets.AWS_CLOUDFRONT }} \
          -e OPENAI_API_KEY_FOR_NEST=${{ secrets.OPENAI_API_KEY_FOR_NEST }} \
          -v volume:${{ secrets.VOLUME }} \
          --restart always \
          --name minori-rag-app-container \
          z00one/minori-rag-app:latest
