name: Docker Image CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Hub SignIn
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build the Docker image
        run: docker build -t minori-rag-app .
      - name: Taging
        run: docker tag minori-rag-app:latest z00one/minori-rag-app:latest
      - name: Push to Dockerhub
        run: docker push z00one/minori-rag-app:latest
