name: Docker Image CI

on:
  pull_request_target:
    types: [closed]
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, '🆗 safe') && github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: z00one
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
