name: Docker Image CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build the Docker image
        run: docker build -t minori-rag-app .
      - name: Taging
        run: docker tag minori-rag-app:latest z00one/minori-rag-app:latest
      - name: Push to Dockerhub
        run: docker push z00one/minori-rag-app:latest
